### ISSUE TITLE
Add zokrates-api to Zokrates+

### ISSUE THREAD

**Issue by alv-around** [ZoKratesPlus/zokrates-api#5]
### Issue Description :x:
Zokrates CLI is hard to embed in automated processes. On the other hand zokrates-js brings performance loss against cli.

### Solution :bulb:
Wrap around the source code of the zokrates library in an API.
Move the zokrates api from the [original repo](https://github.com/alvaro-alonso/blockchain-preprocessor) to Zokrates+ organization to gain more visibility.

Break down of the topics this issue should solve:
- [x] Move source code fro blockchain-preprocessor repository
- [x] Update README.md with instruction how to pull the docker image & and how to open the openAPI specification
- [x] Add badges with zokrates and rocket.rs versions badge
- [x] Add contribution guidelines
- [x] Update License to GNU LGPL3.0
- [x] Setup configuration
- [x] Make repository public
- [x] Add release and build action on release

**Comment by alvaro-alonso** [comment]
@JonathanHeiss @chGoodchild @nikiblume @lucasstuve  feedback is welcome

**Comment by alvaro-alonso** [comment]
@JonathanHeiss any feedback on the ticket is welcome :)

**Comment by JonathanHeiss** [comment]
worked like a charm until proof generation. here I got a 404 with "POST http://0.0.0.0:8000/FF2482276ADCD956ACB349EC598F31C33DA08B210567E5847D46D18C73855365/compute-generate-proof" from Postman

**Comment by alvaro-alonso** [comment]
@JonathanHeiss a 404 means the url is not found. But looking at the proof id (`FF2482276ADCD956ACB349EC598F31C33DA08B210567E5847D46D18C73855365`) it doesn't seem to be the problem.

can you provide the source code and witness use to call the `/compute-generate-proof`  method?
